import { Component } from '@angular/core';

@Component({
  selector: 'app-room-types',
  templateUrl: './room-types.component.html',
  styleUrls: ['./room-types.component.css']
})
export class RoomTypesComponent {
  rooms = [
    { title: "Habitacion 1", bed: "1 ", bath: "2", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room1.jpg'},
    { title: "Habitacion 2", bed: "2", bath: "2", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room3.jpg'},
    { title: "Habitacion 3", bed: "2", bath: "1", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room5.jpg'},
    { title: "Habitacion 4", bed: "2", bath: "1", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room7.jpg'},
    { title: "Habitacion 5", bed: "1", bath: "3", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room8.jpg'},
    { title: "Habitacion 6", bed: "1", bath: "2", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room10.jpg'},
    { title: "Habitacion 7", bed: "3", bath: "2", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room4.jpg'},
    { title: "Habitacion 8", bed: "1", bath: "3", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room2.jpg'},
    { title: "Habitacion 9", bed: "1", bath: "3", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room6.jpg'},
    { title: "Habitacion 10", bed: "3", bath: "1", desc: "Experimenta verdadera comodidad y relajación en nuestra habitación diseñada con estilo. Equipada con comodidades modernas, como una cama acogedora, televisor de pantalla plana e internet de alta velocidad, nuestra habitación ofrece el escape perfecto después de un largo día. Descansa en la tranquila atmósfera y disfruta de una noche de sueño reparador en este refugio acogedor.", url: 'assets/imgs/rooms/room15.webp'},
  ];
}
